# Project name used for labeling outputs
project_name: "project_name"

# Absolute path to the root directory of your project (no trailing slash)
project_dir: "/absolute/path/to/your/project"

# Path to raw FASTQ data (can be relative or absolute)
raw_dir: "/absolute/path/to/your/project/path/to/raw_data"

# Output directories created by the pipeline
trimmed_dir: "/absolute/path/to/your/project/cutadapt_output"
fastqc_dir: "/absolute/path/to/your/project/cutadapt_output/fastqc_output"
mageck_output: "/absolute/path/to/your/project/mageck_output"

# Path to your conda initialization script
conda_path: "/absolute/path/to/conda.sh"

# Conda environment names for each pipeline step
conda_envs:
  cutadapt: "cutadapt"   # Environment for cutadapt
  fastqc: "fastqc"       # Environment for FastQC
  mageck: "mageck"       # Environment for MAGeCK

# List of sample base names matching your FASTQ files
samples:
  - S1_TP0
  - S1_CTRL
  - S1_DRUG
  - S2_TP0
  - S2_CTRL
  - S2_DRUG
